Clean up mysql temp dir.

diff --git a/scripts/run-tests-in-docker-compose b/scripts/run-tests-in-docker-compose
--- a/scripts/run-tests-in-docker-compose
+++ b/scripts/run-tests-in-docker-compose
@@ -5,11 +5,24 @@ set -ex
 ensure_empty_dir(){
   if [ -z "${1}" ]; then
     echo "ERROR: ensure_empty_dir takes a directory as argument." >&2
+    exit 2
+  fi
+  dir="$(cd "${1}" && pwd)"
+  dir_basename="$(basename "${dir}")"
+  parent_dir="$(cd "${dir}"/.. && pwd)"
+  if [ "${dir}" != "${parent_dir}/${dir_basename}" ]; then
+    echo "ERROR: Expected \"${dir}\" to equal \"${parent_dir}/${dir_basename}\"." >&2
     exit 1
   fi
-  mkdir -p "${1}"
-  rm -rf "${1}"
-  mkdir -p "${1}"
+
+  mkdir -p "${dir}"
+  docker run --rm -i \
+    -v "${parent_dir}:/target_parent_dir" \
+    -w "/target_parent_dir" \
+    -e dir_basename="${dir_basename}" \
+    alpine \
+    sh -c 'rm -rf "${dir_basename}"'
+  mkdir -p "${dir}"
 }
 
 PROJECT_DIR="$(cd "$(dirname "$0")"/.. && pwd)"
